[package]
name = "image-showcase"
version = "0.1.0"
authors = ["sisso <sisso@sisso.com.br>"]
edition = "2018"

[profile.dev]
opt-level = 1

[dependencies]
ggez = "0.5.1"
cgmath = { version = "0.17", features = ["mint"]}
mint = "0.5.5"
image = "0.23.13"
rand = "*"
approx = "0.3.2"
