[package]
name = "test-imgui"
version = "0.1.0"
authors = ["sisso <sissobr@gmail.com>"]
edition = "2018"

[dependencies]
ggez = "0.6"

gfx_core = "0.9"
gfx_device_gl = "0.16"

image = "0.23"

imgui = "0.1.0"
imgui-gfx-renderer = "0.1.0"
